### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by aaronlelevier** [toranb/learning-react-and-webpack-2015#1]
Can we please add a `README` to this repo?

jk!

That's cool you're into reactJs.  Scott was telling me, so had to browse your repo's y'all.

**Comment by toranb** [comment]
haha, I'm actually just doing a refresh of what I did back in 2014 (this repo is the start to that "reboot")

I actually got deep into react /react router a year ago and even spoke about it at a regional conference (MidwestJS)

https://www.youtube.com/watch?v=nuiz3IDDK74

The audio is terrible from that so here is another version of that I recorded myself (much better audio)

https://vimeo.com/103201888

Here is the source code for that (won't work anymore but I'm planning to do a refresh of it in Jan 2016)

https://github.com/toranb/react-fireup-clone

**Comment by aronysidoro** [comment]
Cool. I'm gonna watch it later.  Didn't know u were a react guy!
